type: FPN
in_channels: ${backbone.out_channels}
out_channels: 64
start_level: 0
num_outs: 4
norm_cfg:
  type: BN
upsample_cfg:
  mode: nearest
boost_cfg:
  type: PPM
  in_channels: ${backbone.out_channels[3]}
  out_channels: ${backbone.out_channels[3]}
  feat_size: "${eval: ${dataset.img_shape[1]} // 32}"
