type: YOLOXHead
num_classes: ${dataset.num_classes}
num_points: ${dataset.num_points}
input_size: ${dataset.img_shape}
in_channels: [32, 32, 32, 32]
strides: [4, 8, 16, 32]
feat_channels: 96
stacked_convs: 2
decoupled: false
act_cfg:
  type: SiLU
train_cfg:
  assigner:
    type: SimOTAAssigner
test_cfg:
  score_thr: 0.1
  nms:
    type: nms
    iou_threshold: 0.5
