defaults:
  - base
  - export: pld
  - optimizer: adan
  - lr_scheduler: cosine
  - backbone: vovnet
  - _self_

export:
  inputs:
    img: [1, 3, 448, 448]
  output_names:
    - pld_hmax
    - pld_heat
    - pld_offset
    - obs_hmax
    - obs_heat
    - obs_offset
    - seg

task_configs:
  pld: pld.yaml
  # obs: obs.yaml
  # seg: freespace.yaml

model:
  type: MultiDetector
  backbone: ${backbone.params}
  tasks: ${task_configs}

ema:
  enabled: false

wandb:
  enabled: false

trainer:
  find_unused_parameters: true

task_name: onemodel
lr_total: 0.03
batch_size: 48
epochs: 60
