params:
  type: MSCAN
  embed_dims: [32, 64, 160, 256]
  depths: [3, 3, 5, 2]
  mlp_ratios: [8, 8, 4, 4]
  drop_rate: 0.0
  drop_path_rate: 0.1
  norm_cfg:
    type: SyncBN
  init_cfg:
    type: Pretrained
    checkpoint: /mnt/v1/home/zhangkai/pretrained/mscan_t.pth

out_channels: [32, 64, 160, 256]
